repositories:
  - name: wbstack-charts
    url: git+https://github.com/wbstack/deploy/@charts/tool-widar?ref=main

releases:
- name: tool-widar
  namespace: default
  chart: wbstack-charts/tool-widar
  values:
    - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../../../private.yaml

