apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: faster
  labels:
    app.kubernetes.io/managed-by: ManualGit
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true

