controller:
  service:
    loadBalancerIP: 34.141.93.67
    externalTrafficPolicy: Local
  resources:
    #          limits:
    #            cpu: 100m
    #            memory: 64Mi
    requests:
      cpu: 0.100
      memory: 150Mi
#      autoscaling:
#        enabled: false
#        minReplicas: 1
#        maxReplicas: 2
#        targetCPUUtilizationPercentage: 50
#        targetMemoryUtilizationPercentage: 50
  config:
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#block-user-agents
    # https://nginx.org/en/docs/http/ngx_http_map_module.html#map
    block-user-agents: ~*Seekport\sCrawler.*
