repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: platform-nginx
  namespace: default
  chart: bitnami/nginx
  version: 5.2.4
  values:
  - "values.yaml.gotmpl"

environments:
  production:
    values:
      - ./../../../private-production.yaml
  local:
    values:
      - ./../../../private-local.yaml