repositories:
  - name: wbstack-charts
    url: git+https://github.com/toban/deploy/@charts/api?ref=api-fix

releases:
- name: api
  chart: wbstack-charts/api
  namespace: default
  set:
  - name: app.passport.public
    file: ./../../../oauth-public.key
  - name: app.passport.private
    file: ./../../../oauth-private.key
  values:
  - "values.yaml.gotmpl"

environments:
  production:
    kubeContext: gke_wikibase-cloud_europe-west3-a_wbaas-1
    values:
    - ./env/production/base.yaml
    - ./env/production/private.yaml
    - ./../../default.yaml
  local:
    kubeContext: minikube-wbaas
    values:
    - ./env/local/base.yaml
    - ./env/local/private.yaml
    # TODO this should be different for local!
    - ./../../default.yaml