repositories:
  - name: wbstack-charts
    url: git+https://github.com/toban/deploy/@charts/api?ref=api-fix

releases:
- name: api
  chart: wbstack-charts/api
  namespace: default
  set:
  - name: app.passport.public
    file: ./../../../oauth-public.key
  - name: app.passport.private
    file: ./../../../oauth-private.key
  values:
  - "values.yaml.gotmpl"

environments:
  local:
    values:
      - ./../env/local/private.yaml

  production:
    values:
      - ./../../../default.yaml
      - ./../env/production/private.yaml
