repositories:
  - name: wbstack-charts-qs-ui
    url: git+https://github.com/wbstack/deploy/@charts/queryservice-ui?ref=main

releases:
- name: queryservice-ui
  namespace: default
  chart: wbstack-charts-qs-ui/queryservice-ui
  values:
  - "values.yaml"

environments:
  production:
    kubeContext: gke_wikibase-cloud_europe-west3-a_wbaas-1
    values:
      - ./../../../default.yaml
      - ./../../../private-production.yaml
  local:
    kubeContext: minikube-wbaas
    values:
      - ./../../../private-local.yaml