repositories:
  - name: wbstack-charts
    url: git+https://github.com/wbstack/deploy/@charts/tool-quickstatements?ref=main

releases:
- name: tool-quickstatements
  namespace: default
  chart: wbstack-charts/tool-quickstatements
  values:
    - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../../../default.yaml
      - ./../../../private.yaml
