repositories:
- name: jetstack
  url: https://charts.jetstack.io

environments:
  production:
    kubeContext: gke_wikibase-cloud_europe-west3-a_wbaas-1
    values:
    - ./env/production/private.yaml
  local:
    kubeContext: minikube-wbaas
    values:
    - ./env/local/private.yaml

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.5.3
  set:
    - name: installCRDs
      value: true