repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jetstack
  url: https://charts.jetstack.io
- name: mittwald
  url: https://helm.mittwald.de
- name: wbstack-deploy-charts
  url: git+https://github.com/wbstack/deploy/@charts?ref=main

environments:
  production:
    kubeContext: gke_wikibase-cloud_europe-west3-a_wbaas-1
    values:
    - ./env/production/base.yaml
    - ./env/production/private.yaml
    - ./../../default.yaml
  local:
    kubeContext: minikube-wbaas
    values:
    - ./env/local/base.yaml
    - ./env/local/private.yaml
    # TODO this should be different for local!
    - ./../../default.yaml

# Path to helmfiles to process BEFORE releases
# All the nested state files under `helmfiles:` is processed in the order of definition.
helmfiles:
  - path: cert-manager.yaml
    values:
      - foo: null

releases:
################################
# PRODUCTION ONLY
################################
# Only deploy the clusterissuers to production for now, as they won't work locally anyway right now...
- name: clusterissuers
  installed: {{ eq .Environment.Name "production" | toYaml }}
  namespace: cert-manager
  # TODO use something more generic or from wbstack/charts repo
  chart: ./../../charts/wikibase-cloud-clusterissuers
  values:
  # TODO current production uses the email foo@bar.com, once that is fixed, remove this hack...
  - email: {{ .Values.external.letsencrypt.email }}
  - gceProject: {{ .Values.gceProject }}
  # TODO this chart needs certificates for some reason, i probably shouldn't
  - certificates:
    - dnsNames:
        - '*.wikibase.cloud'
        - 'wikibase.cloud'
    - dnsNames:
        - '*.wikibase.dev'
        - 'wikibase.dev'

################################
# ALL ENVIRONMENTS
################################
- name: nginx-ingress
  namespace: kube-system
  chart: stable/nginx-ingress
  version: 1.34.3
  values:
  - "env/{{ .Environment.Name }}/nginx-ingress.values.yaml.gotmpl"

- name: redis
  # This is in the default namespace, as the default ns implies staging?
  namespace: default
  chart: bitnami/redis
  version: 10.5.14
  values:
  - "redis.values.yaml.gotmpl"

- name: ui
  namespace: default
  chart: wbstack-deploy-charts/ui
  values:
  - "env/{{ .Environment.Name }}/ui.values.yaml.gotmpl"

- name: queryservice-ui
  namespace: default
  chart: wbstack-deploy-charts/queryservice-ui
  values:
  - "env/{{ .Environment.Name }}/queryservice-ui.values.yaml.gotmpl"
- name: queryservice
  namespace: default
  chart: wbstack-deploy-charts/queryservice
  values:
  - "env/{{ .Environment.Name }}/queryservice.values.yaml.gotmpl"
- name: queryservice-gateway
  namespace: default
  chart: wbstack-deploy-charts/queryservice-gateway
  values:
  - "env/{{ .Environment.Name }}/queryservice-gateway.values.yaml.gotmpl"
- name: queryservice-updater
  namespace: default
  chart: wbstack-deploy-charts/queryservice-updater
  values:
  - "env/{{ .Environment.Name }}/queryservice-updater.values.yaml.gotmpl"

################################
# Removed deployments
# These should be left here for a short while to allow locel setups to have them removed
################################
- name: kubernetes-secret-generator
  installed: false
  namespace: default
  chart: mittwald/kubernetes-secret-generator