releases:
- name: clusterissuers
  namespace: cert-manager
  chart: ./../../../charts/wikibase-cloud-clusterissuers
  values:
  - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../../../private.yaml
